database:
  host: localhost
  name: myapp
  password: password
  port: 5432
  user: user
features:
  enable_auth: false
  enable_cache: false
  enable_metrics: false
logging:
  file: /var/log/myapp.log
  level: info
  max_size: 10485760
  rotate: true
server:
  debug: false
  host: localhost
  port: 8080
