services:
  nekoconf:
    build:
      context: .
      dockerfile: Dockerfile
    image: k3scat/nekoconf:latest
    container_name: nekoconf
    restart: unless-stopped
    ports:
      # Notes: change the host port if conflicting
      - "8000:8000"
    # Optional: mount a custom config file, if not, you might need to edit the config via the web UI under /config
    # volumes:
    #   - ./config.yaml:/app/config.yaml
    command: ["nekoconf", "server", "--config", "custom-config.yaml"] # Example override
    # Command Examples: 
    # - Enable Event Emission: ["nekoconf", "server", "--config", "custom-config.yaml", "--event", "true"]
    # - Enable Server with Auth: ["nekoconf", "server", "--config", "custom-config.yaml", "--api-key", "your_api_key"]
    # - Enable Server with read-only : ["nekoconf", "server", "--config", "custom-config.yaml", "--read-only", "true"]
    environment:
      # Notes: CONFIG_PATH only supports relative paths
      # Optional: performance boost (safe to ignore if unsupported)
      - DOCKER_BUILDKIT=1
      - COMPOSE_DOCKER_CLI_BUILD=1
    networks:
      - nekoconf-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

networks:
  nekoconf-network:
    driver: bridge
    driver_opts:
      # Avoid naming conflicts; optional, WSL-safe
      com.docker.network.bridge.name: nekoconf-br