name: Dependency Review

on:
  pull_request:
    branches: ["main", "staging"]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high
          deny-licenses: 'GPL-3.0, AGPL-3.0'
          vulnerability-check: true
      
      - name: Scan for vulnerabilities
        uses: pypa/gh-action-pip-audit@v1.0.9
        with:
          inputs: "requirements.txt pyproject.toml"
          output-format: github