name: Code Formatting

# run black and isort on your local machine before pushing changes
# black .
# isort .

on:
  push:
    branches: ["*"]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            setup.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Check imports with isort
        run: |
          isort --check --diff .

      - name: Check formatting with Black
        run: |
          black --check --diff .
          
      - name: Format code (on push to main or staging)
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging')
        run: |
          isort .
          black .
          
      - name: Commit changes
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging')
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: format code with Black and isort"
          file_pattern: "*.py"