name: CI - Publish

on:
  workflow_run:
    workflows: ["CI - Test", "Code Formatting"]
    types:
      - completed
    branches: ["main", "staging"]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_run' && 
      github.event.workflow_run.conclusion == 'success' && 
      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'staging')) || 
      github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Publish package to TestPyPI
      if: github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'staging'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
        verbose: true

    - name: Publish package to PyPI
      if: (github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true