# .github/workflows/publish.yml
name: CI - Publish and Release

on:
  push:
    branches:
      - main # Trigger release only on pushes to main

# Prevent multiple concurrent releases
concurrency:
  group: ${{ github.workflow }}-release
  cancel-in-progress: false # Do not cancel releases once started

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: Publish and Release
    permissions:
      contents: write # Needed to create GitHub releases and tags
      id-token: write # Needed for PyPI trusted publishing (OIDC) - Recommended!
    steps:
      # Generate Token for the GitHub App
    - name: Generate GitHub App Token
      id: generate-token
      # Uses App ID and Private Key secrets to generate a short-lived installation token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.CI_APP_ID }}
        private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ steps.generate-token.outputs.token }}
        fetch-depth: 0
        persist-credentials: true

    # Setup Python - semantic-release might need it or specific tools
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    # Configured with PyPI Trusted Publishing (OIDC)
    # https://docs.pypi.org/trusted-publishers/
    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9
      with:
        github_token: ${{ steps.generate-token.outputs.token }}