name: CI - Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main'

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Generate Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        configuration: ".github/changelog-config.json"
        outputFile: .github/CHANGELOG.md
        failOnError: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: ${{ steps.github_release.outputs.changelog || 'First release' }}

    - name: Update CHANGELOG file
      run: |
        if [ -f CHANGELOG.md ]; then
          echo "# Release ${{ github.ref_name }} - $(date +'%Y-%m-%d')" > temp_changelog.md
          echo "" >> temp_changelog.md
          if [ -n "${{ steps.github_release.outputs.changelog }}" ]; then
            echo "${{ steps.github_release.outputs.changelog }}" >> temp_changelog.md
          else
            echo "First release" >> temp_changelog.md
          fi
          echo "" >> temp_changelog.md
          echo "" >> temp_changelog.md
          cat CHANGELOG.md >> temp_changelog.md
          mv temp_changelog.md CHANGELOG.md
        else
          echo "# Release ${{ github.ref_name }} - $(date +'%Y-%m-%d')" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          if [ -n "${{ steps.github_release.outputs.changelog }}" ]; then
            echo "${{ steps.github_release.outputs.changelog }}" >> CHANGELOG.md
          else
            echo "First release" >> CHANGELOG.md
          fi
        fi

    - name: Commit updated CHANGELOG
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "docs: update CHANGELOG for ${{ github.ref_name }}"
        file_pattern: "CHANGELOG.md"